#+TITLE: Starter Kit Haskell
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[file:starter-kit.org][Emacs Starter Kit]].

* Starter Kit Haskell
  :PROPERTIES:
  :results:  silent
  :END:
Support for editing Haskell

** Setting up cabal
You can skip these steps if you've already setup ghc and cabal
*** Install cabal
**** Linux (Debian/Ubuntu)
#+begin_src sh
  sudo apt-get update
  sudo apt-get install ghc cabal-install
  cabal update
#+end_src
    
**** OS X [with Homebrew]
#+begin_src sh
  brew update
  brew install ghc cabal-install
  cabal update
#+end_src

*** Update cabal
#+start_src sh
   cabal install cabal-install
#+end_src

*** Set path to ~/.cabal/bin
#+begin_src sh
  echo 'PATH=~/.cabal/bin:$PATH'|tee -a ~/.profile
  source ~/.profile
  which cabal
#+end_src

The last line should show you that you are now using the local and
latest version of cabal located in your ~/.cabal/bin directory.

*** Innstall Packages for Development

Haskell modes usually have two components to them. One side is haskell
and the other side is installed and configured in Emacs

We will want to install some basic haskell packages in our ~/.cabal &
~/.ghc user directories. This makes them available along side cabal
for doing development on your projects.

Running those commands in the shell might take some time - emacs
appears to be frozen; trust me, it's not
#+begin_src sh
  cabal install happy alex ;# needed but not listed as dependency
#+end_src

Paste the following into your terminal:


** Pretty lambdas
pretty lambdas in Haskell code
#+begin_src emacs-lisp
  (defun pretty-lambdas-haskell ()
    (font-lock-add-keywords
     nil `((,(concat "(?\\(" (regexp-quote "\\") "\\)")
            (0 (progn (compose-region (match-beginning 1) (match-end 1)
                                      ,(make-char 'greek-iso8859-7 107))
                      nil))))))
#+end_src


** Haskell Mode

#+begin_src emacs-lisp
  (use-package haskell-mode
    :ensure t
    :defer t
    :config
    (add-hook 'haskell-mode-hook 'run-starter-kit-coding-hook)
    (when (window-system)
      (add-hook 'haskell-mode-hook 'pretty-lambdas-haskell))
    (add-hook 'haskell-mode-hook 'interactive-haskell-mode)
    (add-hook 'haskell-mode-hook 'flyspell-prog-mode)
    (add-hook 'haskell-mode-hook 'haskell-indentation-mode))

    ;; Ignore compiled Haskell files in filename completions
    (add-to-list 'completion-ignored-extensions ".hi")
#+end_src

** Intero Mode

#+BEGIN_SRC emacs-lisp
(use-package intero
  :ensure t
  :defer t
  :init
  (add-hook 'haskell-mode-hook 'intero-mode))
#+END_SRC
